import type { Metadata } from "next";
import { Navbar } from "@/components/global/nav-bar";
import { Inter } from "next/font/google";
import "@fontsource/allison";
import "./globals.css";
import { Footer } from "@/components/global/footer";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${inter.className} antialiased`}>
        <Navbar />
        {children}

        <Footer />
      </body>
    </html>
  );
}
